lesson3
Neffesto/Basic-JavaScript-Course pull request #3
Opened 2021-07-18 15:05 UTC by Neffesto

Сдаю  ДЗ 3

2021-07-18 23:18 UTC, Om1X requested changes

2021-07-18 23:18 UTC, Om1X commented on lesson 3/basket_price.js
> +    });
тут можно было обойтись одним reduce

2021-07-18 23:18 UTC, Om1X commented on lesson 3/basket_price.js
> +    });
также функция должна возвращать результат

2021-07-18 23:18 UTC, Om1X commented on lesson 3/basket_price.js
> +console.log(result);
result нигде не объявлен

2021-07-19 16:02 UTC, Neffesto commented
ДЗ Сдано

2021-07-19 16:02 UTC, merged